### ISSUE TITLE
Make a Task that fetches the code from GitHub

### ISSUE THREAD

**Issue by RobbieMcKinstry** [alligrader/jobs#4]
# Abstract

We have a system to execute Tasks (by walking the concurrent tree). This issue is the implementation of a particular Task which pulls a particular commit from GH onto the local container.

# Introduction

The GitHub API provides a means to download the source code from the repository. Their API lets you specify which Git ref you want to download. In our case, if the user Bill pushes a commit to the branch `bills-branch`, then we want to download the last commit Bill pushed so we can run our tests against it. [This is how GH documents](https://developer.github.com/v3/repos/contents/#get-archive-link) this feature.

Suppose the full commit ref is `0c217921f1e5b1648e9e6ae6f511bcd9c9559211`. This is provided to use by the webhook GH sends to us when we set up our webserver. Then, we make a request back to GH to get back an archieve of the commit

    GET /repos/Bill/Bills-Repo/zip/0c217921f1e5b1648e9e6ae6f511bcd9c9559211

Once we follow the redirect, we'll download a zipfile containing all of the repo's code, checked out to that particular ref.

# Next Steps

Once we have the zipfile, we need to save it to disk. We can store the zipfile in [a temp file](https://golang.org/pkg/io/ioutil/#TempFile)  and then [create a temporary directory](https://golang.org/pkg/io/ioutil/#TempDir) in which to [unpack it](https://github.com/mholt/archiver#library-use).

# TODO List

Here's a summary of the steps you need to take to complete this issue.

- [ ] Pull out of the ctx the variables the OAuth key (the access credentials to the GH API), the repo name
- [ ] Construct the URL from the ctx variables
- [ ] Make a request to that link, following all redirects
- [ ] Save the download zipfile to a temp file
- [ ] Open that temp file into a clean temp directory
- [ ] Update the context with the path to the temp directory
- [ ] Write a test for your Visitable type that creates a context with a publically-accessible Git repo on GH, and then runs the task, finally inspecting the filesystem to ensure that the download was correctly unzipped.

Here's a link to an example webhook payload: https://developer.github.com/v3/activity/events/types/#webhook-payload-example-22
From this payload, the "after" ref will be injected into the context for you to use, as will the `repository.full_name` variable.

# Other Notes

I would very much like to write the test for you so that you get the method heads done for you, and that the variables are approperately injected into the context. I'd love to do that this weekend, but I'm not sure if I'll have the time. Hopefully I will.

**Comment by RobbieMcKinstry** [comment]
Completed
